[tool.poetry]
name = "teste-backend-amicci"
version = "0.1.0"
description = ""
authors = ["lucashamaguchi <lucas@hamaguchi.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
