# Generated by Django 5.0.1 on 2024-01-28 17:24

from django.db import migrations, utils
from amicci_app.models import Category

categories = [
    {
        "id": 1,
        "name": "Novo Produto",
        "description": "Novo Produto",
    },
    {
        "id": 2,
        "name": "Troca de Fornecedor",
        "description": "Troca de Fornecedor",
    },
    {
        "id": 3,
        "name": "Reformulação de Produto",
        "description": "Reformulação de Produto",
    }
]


def create_categories(*args, **kwargs):
    for category in categories:
        try:
            Category.objects.create(**category)
        except utils.IntegrityError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('amicci_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, migrations.RunPython.noop)
    ]
