# Generated by Django 5.0.1 on 2024-01-28 17:47

from django.db import migrations
from django.core.management.color import no_style
from django.db import connection

from amicci_app.models import Category


def reset_sequence(*args, **kwargs):
    sequence_sql = connection.ops.sequence_reset_sql(no_style(), [Category])
    with connection.cursor() as cursor:
        for sql in sequence_sql:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('amicci_app', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.RunPython(reset_sequence, migrations.RunPython.noop)
    ]
