# Generated by Django 5.0.1 on 2024-01-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amicci_app', '0004_reset_categories_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('responsible', models.CharField()),
                ('category', models.CharField()),
                ('release_date', models.CharField()),
                ('availabe', models.IntegerField()),
                ('retailer', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amicci_app.retailer')),
            ],
        ),
        migrations.AddField(
            model_name='retailer',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='amicci_app.vendor'),
        ),
    ]
