# Generated by Django 5.0.1 on 2024-01-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amicci_app', '0005_retailer_vendor_briefing_retailer_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='briefing',
            old_name='availabe',
            new_name='available',
        ),
    ]
