# Generated by Django 5.0.1 on 2024-01-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amicci_app', '0007_briefing_created_at_briefing_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amicci_app.category'),
        ),
    ]
